version: '3'
services:
  golang_service:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - KAFKA_URL=kafka:9092

  audio_service:
    build: ./machine-learning/audio_service
    ports:
      - "5001:5001"
    environment:
      - KAFKA_URL=kafka:9092

  video_service:
    build: ./machine-learning/video_service
    ports:
      - "5002:5002"
    environment:
      - KAFKA_URL=kafka:9092

  text_service:
    build: ./machine-learning/text_service
    ports:
      - "5003:5003"
    environment:
      - KAFKA_URL=kafka:9092

  elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
